### ISSUE TITLE
API 2 of 3

### ISSUE THREAD

**Issue by shannonbaldwin** [shannonbaldwin/empoweredhome.ai#1]
@codextiny

[https://empoweredhome.ai/home/](url)

U: [support@homeowner.ai](mailto:support@homeowner.ai)
pw:M!l3st0nesL@bs

Please add API pop up to:

Get Started in header
Search bar in hero image (please make button the primary color)
Get Started button in CTA prefooter section

**Comment by shannonbaldwin** [comment]
@codextiny
Can you please tell me how to decrease padding here?

![image](https://github.com/user-attachments/assets/72cc8156-7e32-47cb-b65a-d3e091219aa3)

**Comment by codextiny** [comment]
@shannonbaldwin 

popup added,

![image](https://github.com/user-attachments/assets/d001ae13-9290-40ca-8f46-c64b0b944f5e)
its height not padding, you can adjust by changing value, please see above screenshot ...
